%This function is used to change the different parameters,
%either characteristics or default settings, after the analysis

function change_parameters()
load('Spikes.mat','file');
name = 'Change parameters';
current = 1;

for i=1:length(file)
    string{i} = file(i).Name;
end
h1 = figure(...
    'Position',[500 170 500 500],...
    'MenuBar','none',...
    'NumberTitle','off',...
    'Name',name);

movegui(h1,'center');

uicontrol(h1,'style','text',...
         'Position',[10 360 300 100],... 
         'String','Choose the file whose settings you want to change :');
     
m = uicontrol(h1,'Style','popupmenu',...
    'Position', [300 385 140 80],...
    'String',string,...
    'Callback',@selection);

% Creation of the object Uicontrol change Detection Parameters 
uicontrol(h1,'style','pushbutton',...
         'units','normalized',...
         'FontWeight','bold',...
         'position',[0.3 0.6 0.4 0.2],...
         'string','Change detection parameters',...
         'callback',@Parameters,...
         'Enable','on',...
         'tag','bouton_detection_parameters');
     
% Creation of the object Uicontrol Change Characteristics
uicontrol(h1,'style','pushbutton',...
         'units','normalized',...
         'FontWeight','bold',...
         'position',[0.3 0.3 0.4 0.2],...
         'string','Change characteristics of the file',...
         'callback',@WindowCharacteristics,...
         'Enable','on',...
         'tag','bouton_detection_parameters');
     
     % Creation of the object Uicontrol Change Characteristics
uicontrol(h1,'style','pushbutton',...
         'units','normalized',...
         'FontWeight','bold',...
         'position',[0.40 0.1 0.2 0.1],...
         'string','Finish',...
         'callback',@finish,...
         'Enable','on',...
         'tag','bouton_finish');

    
    
    function selection(src,event)
            current = m.Value;
    end


    function Parameters(obj,event)
        load('Spikes.mat','file');
        window_Parameters(current,file);
    end

    function WindowCharacteristics(obj,event)
        load('Spikes.mat','file');
        window_characteristics(current,file);
    end

    function finish(obj,event)
        close(gcf);
        Analyze();
        load('Spikes.mat','file'); 
        save('SpikesPreviousAnalysis.mat','file'); % get previous .mat file
        windowAnalyze();
    end

end

%% Window allowing to choose between Confusion Matrix, Display spikes, 
%%% changing parameters, 2D scalp view, export to XML file
%%% and excport statistics to excel file
function windowAnalyze()

handles.fig1 = figure('units','pixels',...
            'position',[550 250 380 380],...
            'numbertitle','off',...
            'Name','Spike detection',...
            'menubar','none',...
            'tag','interface');
        
% Creation of the object Uicontrol Confusion Matrix 
     handles.matrice = uicontrol(handles.fig1,'style','pushbutton',...
     'units','normalized',...
     'FontWeight','bold',...
     'position',[0.1 0.75 0.3 0.2],...
     'string','Confusion Matrix',...
     'callback',@Matrix,...
     'Enable','on',...
     'tag','bouton_matrix');  

 
% Creation of the object Uicontrol Display 
     handles.display = uicontrol(handles.fig1,'style','pushbutton',...
     'units','normalized',...
     'FontWeight','bold',...
     'position',[0.6 0.75 0.3 0.2],...
     'string','Display',...
     'callback',@DisplayAlgo,...
     'tag','bouton_display');
 
 
 % Creation of the object Uicontrol Change Parameters 
     handles.change = uicontrol(handles.fig1,'style','pushbutton',...
     'units','normalized',...
     'FontWeight','bold',...
     'position',[0.1 0.5 0.3 0.2],...
     'string','Change parameters',...
     'callback',@changeParameters,...
     'tag','bouton_parameters');
 
 
 % Creation of the object Uicontrol graphical view in 2D 
 handles.view_2d = uicontrol(handles.fig1,'style','pushbutton',...
     'units','normalized',...
     'FontWeight','bold',...
     'position',[0.6 0.5 0.3 0.2],...
     'string','Graphical view in 2D',...
     'callback',@view,...
     'tag','bouton_2D');

 
 % Creation of the object Uicontrol export to XML file
 uicontrol(handles.fig1,'style','pushbutton',...
     'units','normalized',...
     'FontWeight','bold',...
     'position',[0.6 0.25 0.3 0.2],...
     'string','Export to XML File',...
     'callback',@createXML,...
     'tag','bouton_xml');
 
 
  % Creation of the object Uicontrol create excel file with statistics
  uicontrol(handles.fig1,'style','pushbutton',...
     'units','normalized',...
     'FontWeight','bold',...
     'position',[0.1 0.25 0.3 0.2],...
     'string','Excel statistics',...
     'callback',@excelStat,...
     'tag','bouton_excel');
 

load('Spikes.mat','file');

% enable confusion matrix if no experts and creates cells for listbox
 for i=1:length(file)
     if i == 1
        fileName = {[file(1).Name '  ' num2str(file(1).Duration) ' seconds']};
        file(1).ChosenFile = 1;
     else
        fileName = [fileName [file(i).Name '  ' num2str(file(i).Duration) ' seconds']];
        file(i).ChosenFile = 0;
     end
     if file(1).nbExp == 0
         if file(i).nbExp == 0
            set(handles.matrice,'Enable','off');
         else
             set(handles.matrice,'Enable','on');
         end
     end
 end
 
 save('Spikes.mat','file');

 % Creation of the object Uicontrol Listbox to choose the file to
 % manipulate

 uicontrol(handles.fig1,'Style', 'listbox',...
         'Units','normalized',...
         'Position',[0.1 0.05 0.8 0.15],... %[550 250 380 380]
         'string',fileName,... 
         'Callback', @ChangeCurrentFile);
 
end

%% Analyze the confusion matrix for all files
function Matrix(~,~)
    Confusion_matrix();  
end 
    
%% Analyze the different EEG to display for chosen file
function DisplayAlgo(~,~)
    Display_spikes();  
end

%% Launch a window to change parameters of all the files
function changeParameters(~,~)
    close(gcf);
    change_parameters();
end

%% Launch a window to display a graphic view in 2D for chosen file
function view(~,~) 
    %load('Spikes.mat','file');
    scalp();
end

%% Launch the CreateXMLfile function for chosen file
function createXML(~,~) 
    load('Spikes.mat','file');
    for CurrentRecording = 1:length(file)
        if (file(CurrentRecording).ChosenFile == 1)
            CreateXMLfile(CurrentRecording);
        end
    end
end

%% Create excel file with relevant statistics
function excelStat(~,~) 
    excel_stats();
end

%% Choose the current working file using the listbox
function ChangeCurrentFile(obj,event) 
    ChosenFile = get(obj,'value');
    load('Spikes.mat','file');
    for CurrentRecording = 1:length(file)
        if ChosenFile == CurrentRecording
            file(CurrentRecording).ChosenFile = 1;
        else
            file(CurrentRecording).ChosenFile = 0;
        end
    end
    save('Spikes.mat','file');
    disp('Not fully implemented yet...');
end



%     function windowAnalyze()
% 
% handles.fig1 = figure('units','pixels',...
%             'position',[550 250 300 270],...
%             'numbertitle','off',...
%             'Name','Spike detection',...
%             'menubar','none',...
%             'tag','interface');
% % Creation of the object Uicontrol Confusion Matrix 
%      handles.matrice = uicontrol(handles.fig1,'style','pushbutton',...
%      'units','normalized',...
%      'FontWeight','bold',...
%      'position',[0.27 0.7 0.4 0.2],...
%      'string','Confusion Matrix',...
%      'callback',@Matrix,...
%      'Enable','on',...
%      'tag','bouton_matrix');  
%  
%  load('Spikes.mat','file');
%  for i=1:length(file)
%      if file(1).nbExp == 0
%          if file(i).nbExp == 0
%             set(handles.matrice,'Enable','off');
%          else
%              set(handles.matrice,'Enable','on');
%          end
%      end
%  end
%  
% % Creation of the object Uicontrol Display 
%      handles.display = uicontrol(handles.fig1,'style','pushbutton',...
%      'units','normalized',...
%      'FontWeight','bold',...
%      'position',[0.27 0.45 0.4 0.2],...
%      'string','Display',...
%      'callback',@DisplayAlgo,...
%      'tag','bouton_display');
%  
%  
%  
%  % Creation of the object Uicontrol Change Parameters 
%      handles.param = uicontrol(handles.fig1,'style','pushbutton',...
%      'units','normalized',...
%      'FontWeight','bold',...
%      'position',[0.27 0.2 0.4 0.2],...
%      'string','Change parameters',...
%      'callback',@changeParameters,...
%      'tag','bouton_parameters');
%  
%  
%  
%     end
% 
%     
% end
% %% Launch a window to change parameters of the file(s)
%     function changeParameters(obj,event)
%     change_parameters();
%     end
%     %% Analyze the confusion matrix
% function Matrix(obj,event)
%     Confusion_matrix();  
% end 
%     
% %% Analyze the different EEG to display
% function DisplayAlgo(obj,event)
%     Display_spikes();  
% end