function scalp()
% This function creates a window 
% in which the user can see a 2D view of the spikes density
% Author : Kevin Nzeyimana (kevin.nzeyimana@reseau.eseo.fr)

count_spikes();
load('Spikes.mat','file');
for current = 1:length(file)
    if file(current).ChosenFile == 1

        name = ['Scalp for ' file(current).Name];

        %% Retrieve the list of the electrodes selected
        for i=1:length(file(current).channels)
            if i == 1
                list1 = file(current).channels(i).Name;
                list = list1;
            else
                list1 = file(current).channels(i).Name;
                list = [list ' ' list1];
            end
        end


        h1 = figure(...
            'Position',[400 100 800 800],...
            'MenuBar','none',...
            'NumberTitle','off',...
            'Name',name,...
            'Color', 'w',...
            'Resize','off');

        movegui(h1,'center'); 

        im = imread('scalp eeg.png');
        view = imshow(im);        % Display the image
        % view.InitialMagnification = 'fit';
        set(gca,'visible','off');
        hold on;            % Add subsequent plots to the image
        % Adding the circles corresponding to the channels
        %FP1-F3
        handles(1).circle = plot(600,450,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','Fp1 -  F3 ');
        %FP2-F4           
        handles(2).circle = plot(1190,450,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','Fp2 -  F4 ');
        %F4-C4                
        handles(3).circle = plot(1190,710,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','F4  -  C4 ');
        %F3-C3                
        handles(4).circle = plot(600,710,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','F3  -  C3 ');
        %C3-P3                
        handles(5).circle = plot(595,1010,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','C3  -  P3 ');
        %P3-O1                
        handles(6).circle = plot(595,1330,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','P3  -  O1 ');                 
        %T4-T6
        handles(7).circle = plot(1490,1010,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','T4  -  T6 ');
        %T6-O2                
        handles(8).circle = plot(1355,1340,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','T6  -  O2 ');
        %F7-T3                
        handles(9).circle = plot(280,710,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','F7  -  T3 ');
        %T3-T5                
        handles(10).circle = plot(290,1010,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','T3  -  T5 ');                
        %T5-O1                
        handles(11).circle = plot(400,1330,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','T5  -  O1 ');
        %Fz-Cz                
        handles(12).circle = plot(890,710,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','Fz  -  Cz ');
        %Cz-Pz                
        handles(13).circle = plot(890,1010,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','Cz  -  Pz ');
        %F9-T9                
        handles(14).circle = plot(70,740,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','F9  -  T9 ');

        %T9-P9                
        handles(15).circle = plot(70,1000,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','T9  -  P9 ');
        %F10-T10                
        handles(16).circle = plot(1700,740,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','F10 -  T10');
        %T10-P10                
        handles(17).circle = plot(1700,1000,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','T10 -  P10');
        %FP1-F7
        handles(18).circle = plot(380,450,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','Fp1 -  F7 ');                

        %FP2-F8           
        handles(19).circle = plot(1380,450,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','Fp2 -  F8 ');
        %F8-T4                
        handles(20).circle = plot(1490,710,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','F8  -  T4 ');                
        %C4-P4                
        handles(21).circle = plot(1190,1010,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','C4  -  P4 ');         
        %P4-O2                
        handles(22).circle = plot(1190,1340,'o',... % Note that y is inverted
                            'MarkerFaceColor','none',...
                            'MarkerSize',16,...
                            'MarkerEdgeColor','black',...
                            'Tag','P4  -  O2 ');

        color = 'w';
        font_size = 15;
        handles(1).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.35 .77 0.05 0.045],... 
                     'String','Fp1',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);



        handles(2).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.48 .77 0.05 0.045],... 
                     'String','Fpz',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);
        handles(3).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.61 .77 0.05 0.045],... 
                     'String','Fp2',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(4).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.14 .59 0.047 0.045],... 
                     'String','F9',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);         

        handles(5).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.22 .62 0.047 0.045],... 
                     'String','F7',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(6).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.35 .62 0.047 0.045],... 
                     'String','F3',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);
        handles(7).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.48 .62 0.047 0.045],... 
                     'String','Fz',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);
        handles(8).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.61 .62 0.047 0.045],... 
                     'String','F4',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);
        handles(9).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.73 .62 0.047 0.045],... 
                     'String','F8',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(10).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.82 .59 0.05 0.045],... 
                     'String','F10',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);


        handles(11).ch = uicontrol(h1,'style','text',...
                         'Units','normalized',...
                         'Position',[0.11 .485 0.047 0.045],... 
                         'String','T9',...
                         'BackgroundColor',color,...
                         'FontSize',font_size);
        handles(12).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.21 .485 0.047 0.045],... 
                     'String','T3',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(13).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.35 .485 0.047 0.045],... 
                     'String','C3',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(14).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.48 .485 0.047 0.045],... 
                     'String','Cz',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(15).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.61 .485 0.047 0.045],... 
                     'String','C4',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(16).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.75 .485 0.047 0.045],... 
                     'String','T4',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(17).ch = uicontrol(h1,'style','text',...
                         'Units','normalized',...
                         'Position',[0.84 .485 0.05 0.045],... 
                         'String','T10',...
                         'BackgroundColor',color,...
                         'FontSize',font_size);         

        handles(18).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.15 .3 0.047 0.045],... 
                     'String','P9',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);         

        handles(19).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.23 .29 0.047 0.045],... 
                     'String','T5',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(20).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.35 .29 0.047 0.045],... 
                     'String','P3',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(21).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.48 .29 0.047 0.045],... 
                     'String','Pz',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(22).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.61 .29 0.047 0.045],... 
                     'String','P4',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(23).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.72 .29 0.047 0.045],... 
                     'String','T6',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(24).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.81 .3 0.05 0.045],... 
                     'String','P10',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);          

        handles(25).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.35 .155 0.047 0.045],... 
                     'String','O1',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(26).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.48 .155 0.047 0.045],... 
                     'String','Oz',...
                     'BackgroundColor',color,...
                     'FontSize',font_size);

        handles(27).ch = uicontrol(h1,'style','text',...
                     'Units','normalized',...
                     'Position',[0.605 .1575 0.047 0.045],... 
                     'String','O2',...
                     'BackgroundColor',color,...
                     'FontSize',font_size); 

        %% Legend

        newmap = jet(10);
        colormap(newmap);
        c = colorbar('YTickLabel', num2cell(0:2:20));
        c.Label.String = 'spikes per minutes';
        c.Position  = [0.91 0.1 0.02 0.7];
        hold off;    
        for i=1:length(newmap)
            if i == 1
                threshold(i).value = 2;
                threshold(i).color = newmap(i,:);
            else
                threshold(i).value = threshold(i-1).value +2;
                threshold(i).color = newmap(i,:);
            end
        end
           % Any subsequent plotting will overwrite the image


        %% Display the channels selected
        for i=1:length(handles)
            channel = handles(i).ch.String;
            handles(i).ch.Visible = 'off';
            find = contains(list,channel);
            if find
                handles(i).ch.Visible = 'on';
            end
        end


        %% Display & Colouring the circles depending on the number of spikes per minutes

        for i=1:length(handles)
            if ~isempty(handles(i).circle)
                handles(i).circle.Visible = 'off';
                for j=1:length(file(current).channels)
                    find = isequal(handles(i).circle.Tag,file(current).channels(j).Name);
                    if find
                        handles(i).circle.Visible = 'on';
                        if file(current).channels(j).spikes_min < threshold(1).value
                            handles(i).circle.MarkerFaceColor = threshold(1).color; 
                        elseif file(current).channels(j).spikes_min < threshold(2).value
                            handles(i).circle.MarkerFaceColor = threshold(2).color; 
                        elseif file(current).channels(j).spikes_min < threshold(3).value
                            handles(i).circle.MarkerFaceColor = threshold(3).color; 
                        elseif file(current).channels(j).spikes_min < threshold(4).value
                            handles(i).circle.MarkerFaceColor = threshold(4).color; 
                        elseif file(current).channels(j).spikes_min < threshold(5).value
                            handles(i).circle.MarkerFaceColor = threshold(5).color; 
                        elseif file(current).channels(j).spikes_min < threshold(6).value
                            handles(i).circle.MarkerFaceColor = threshold(6).color; 
                        elseif file(current).channels(j).spikes_min < threshold(7).value
                            handles(i).circle.MarkerFaceColor = threshold(7).color; 
                        elseif file(current).channels(j).spikes_min < threshold(8).value
                            handles(i).circle.MarkerFaceColor = threshold(8).color; 
                        elseif file(current).channels(j).spikes_min < threshold(9).value
                            handles(i).circle.MarkerFaceColor = threshold(9).color; 
                        else
                            handles(i).circle.MarkerFaceColor = threshold(10).color;
                        end
                    end
                end
            end
        end



        %% Heatmap

        % Convert hexadecimal color code to 1-by-3 RGB array (0~1 each)
        % From the 2019 version, it is no longer need to use convert function
    %         function color = convert(str)
    %             color = sscanf(str(2:end),'%2x%2x%2x',[1 3])/255;
    %         end

        % % A copy of the names of the electrodes in form of a cell
        % for k=1:length(electrodes)
        %     electrodes_list{k} = electrodes(k).Name;
        % end
        % electrodes_list = unique(electrodes_list); % avoid to have many times the same electrode
        % 
        % 
        % % Count spikes related to each electrode (each time an electrode is
        % %is involved in a detection)
        % electrodes_2 = struct([]);
        % for k =1:length(electrodes_list)
        %     file(current).electrodes_2(k).Name = electrodes_list{k};
        %     file(current).electrodes_2(k).spikes = 0;
        %     for n = 1:length(electrodes)
        %         
        %         if file(current).electrodes_2(k).Name == electrodes(n).Name
        %             file(current).electrodes_2(k).spikes = file(current).electrodes_2(k).spikes + electrodes(n).spikes;
        %         end
        %     end
        % end

        % % load heatmap scores
        % load('heatmap.mat','heatmap');
        % for i=15:16
        %     for j=11:12
        %         heatmap(i,j) = 30;
        %     end
        % end
        % heatmap = double(heatmap); % conversion single to double
        % 
        % % use exp to enforce contrast
        % heatmap = exp(heatmap * 0.02);
        % 
        % % choose colormap
        % colormap('parula')
        % 
        % % resize the heatmap to the image size
        % heatmap = imresize(heatmap, [h, w]);
        % maxScores = max(max(heatmap));
        % minScores = min(min(heatmap));
        % 
        % % display the image and the heatmap in different plot
        % % figure(1), subplot(1,3,1), imagesc(im); axis off, axis image, title('image')
        % % figure(1), subplot(1,3,2), imagesc(heatmap); axis off, axis image, title('cat heatmap')
        % 
        % % normalized the heatmap: all values are in the range [0, 1]
        % normalizedHeatmap = (heatmap - minScores) / (maxScores - minScores);
        % 
        % % display the image
        % %figure, imagesc(im), axis image, title('image with heatmap');     
        % hold on
        % hImg = imagesc(255 * normalizedHeatmap); axis off, caxis([0 255]);
        % 
        % 
        % % R = hImg(:,:,1); 
        % % G = hImg(:,:,2); 
        % % B = hImg(:,:,3);
        % % for i=1:length(handles)    
        % %     set(handles(i).ch,'backgroundcolor','none');
        % % end
        % % the alpha parameter change the transparency of the heatmap
        % alpha = 0.35;
        % set(hImg, 'AlphaData', alpha);
        % hold off

    end
end
end