function window_Parameters(current,file)
% This function creates a window 
% in which the user can change the detection parameters
% of the selected file
% Author : Kevin Nzeyimana (kevin.nzeyimana@reseau.eseo.fr)

DetectionParameters = file(current).DetectionParameters;
    name = ['Settings for ' file(current).Name];
    handles.fig1 = figure('units','pixels',...
            'position',[550 250 500 450],...
            'numbertitle','off',...
            'name',name,...
            'menubar','none',...
            'tag','interface');

    handles.save = uicontrol(...
    'Parent',   handles.fig1, ...
    'Units',    'pixels', ...
    'Position', [410 10 80 20], ...
    'String',   'Apply',...
    'Callback',@(obj,event)apply(obj));

   handles.pane(1) = uipanel(...
    'Parent',   handles.fig1, ...
    'Units',    'pixels', ...
    'Position', [10 330 480 100], ...
    'Title', 'General Parameters', ...
    'BackgroundColor', get(handles.fig1, 'Color'));

    uicontrol(handles.pane(1),'style','text',...
         'Units','normalized',...
         'Position',[0 0.6 0.6 0.2],... 
         'String','Minimum distance between two spikes (ms) : ');

    handles.minDistance2Spikes = uicontrol(handles.pane(1),...
         'style','edit',...
         'Units','normalized',...
         'Position',[0.75 0.6 0.1 0.2],...
         'String',num2str(DetectionParameters.MinimumDistance2Spikes),...
         'tag','minDistance2Spikes');

    uicontrol(handles.pane(1),'style','text',...
         'Units','normalized',...
         'Position',[0 0.3 0.6 0.2],... 
         'String','Window length (ms) : ');

    handles.windowLength = uicontrol(handles.pane(1),...
         'style','edit',...
         'Units','normalized',...
         'Position',[0.75 0.3 0.1 0.2],...
         'String',num2str(DetectionParameters.WindowLength),...
         'tag','windowLength');

    handles.pane(2) = uipanel(...
    'Parent',   handles.fig1, ...
    'Units',    'pixels', ...
    'Position', [10 200 480 120], ...
    'Title',    'Generic Spike Detection Parameters', ...
    'BackgroundColor', get(handles.fig1, 'Color'));

%     uicontrol(handles.pane(2),'style','text',...
%          'Units','normalized',...
%          'Position',[0 0.1 0.6 0.2],... 
%          'String','Coefficient for template amplitude : ');
% 
%     handles.amplitude = uicontrol(handles.pane(2),...
%          'style','edit',...
%          'Units','normalized',...
%          'Position',[0.75 0.15 0.1 0.15],...
%          'String',num2str(DetectionParameters.GenericTemplateAmplitudeCoef),...
%          'tag','amplitude');

    uicontrol(handles.pane(2),'style','text',...
         'Units','normalized',...
         'Position',[0 0.7 0.6 0.2],... 
         'String','Cross-correlation threshold of the generic template : ');

    handles.crossCorrelationThresholdGT = uicontrol(handles.pane(2),...
         'style','edit',...
         'Units','normalized',...
         'Position',[0.75 0.75 0.1 0.15],...
         'String',num2str(DetectionParameters.GenericCrossCorrelationThresh),...
         'tag','crossCorrelationThresholdGT');

     uicontrol(handles.pane(2),'style','text',...
         'Units','normalized',...
         'Position',[0 0.4 0.6 0.2],... 
         'String','Features threshold of the generic template : ');

    handles.featuresGT = uicontrol(handles.pane(2),...
         'style','edit',...
         'Units','normalized',...
         'Position',[0.75 0.45 0.1 0.15],...
         'String',num2str(DetectionParameters.GenericFeaturesThresh),...
         'tag','featuresGT');


    handles.pane(3) = uipanel(...
    'Parent',   handles.fig1, ...
    'Units',    'pixels', ...
    'Position', [10 40 480 150], ...
    'Title',    'Patient Specific Spike Detection Parameters', ...
    'BackgroundColor', get(handles.fig1, 'Color'));

    uicontrol(handles.pane(3),'style','text',...
         'Units','normalized',...
         'Position',[0 0.75 0.7 0.2],... 
         'String','Cross-correlation threshold of the cluster specific template : ');

    handles.crossCorrelationThresholdST = uicontrol(handles.pane(3),...
         'style','edit',...
         'Units','normalized',...
         'Position',[0.75 0.82 0.1 0.12],...
         'String',num2str(DetectionParameters.PatientSpecificCrossCorrelationThresh),...
         'tag','crossCorrelationThresholdST');

    uicontrol(handles.pane(3),'style','text',...
         'Units','normalized',...
         'Position',[0 0.57 0.6 0.2],... 
         'String','Features threshold of the cluster specific template : ');

    handles.featuresST = uicontrol(handles.pane(3),...
         'style','edit',...
         'Units','normalized',...
         'Position',[0.75 0.64 0.1 0.12],...
         'String',num2str(DetectionParameters.PatientSpecificFeaturesThresh),...
         'tag','featuresST');

     uicontrol(handles.pane(3),'style','text',...
         'Units','normalized',...
         'Position',[0 0.39 0.6 0.2],... 
         'String','Minimum SWI : ');

    handles.minSWI = uicontrol(handles.pane(3),...
         'style','edit',...
         'Units','normalized',...
         'Position',[0.75 0.46 0.1 0.12],...
         'String',num2str(DetectionParameters.PatientSpecificMinimumSWI),...
         'tag','minSWI');

    uicontrol(handles.pane(3),'style','text',...
         'Units','normalized',...
         'Position',[0 0.21 0.6 0.2],... 
         'String','Minimum percentage of spikes in a cluster : ');

    handles.clusterSelectionThresh = uicontrol(handles.pane(3),...
         'style','edit',...
         'Units','normalized',...
         'Position',[0.75 0.28 0.1 0.12],...
         'String',num2str(DetectionParameters.ClusterSelectionThresh),...
         'tag','clusterSelectionThresh');
     
     uicontrol(handles.pane(3),'style','text',... %Check_spikes Threshold button
         'Units','normalized',...
         'Position',[0 0.03 0.6 0.2],... 
         'String','Threshold for the phase opposition : ');

    handles.CheckThresh = uicontrol(handles.pane(3),...
         'style','edit',...
         'Units','normalized',...
         'Position',[0.75 0.1 0.1 0.12],...
         'String',num2str(DetectionParameters.CheckThresh),...
         'tag','CheckThresh');
     
    % Update handles structure
    guidata(handles.fig1, handles);
    
    function apply(~,~)

    handles = guihandles(gcbf);
    
    if exist('Spikes.mat','file') == 2 %to check if there is already a file and if so, load it
        load('Spikes.mat','file');
    end
    
    % General parameters
    file(current).DetectionParameters.MinimumDistance2Spikes = str2double(get(handles.minDistance2Spikes,'String')); % ms
    file(current).DetectionParameters.WindowLength = str2double(get(handles.windowLength,'String')); % ms

    % Generic spike detection parameters
    file(current).DetectionParameters.GenericCrossCorrelationThresh = str2double(get(handles.crossCorrelationThresholdGT,'String')); % Cross-correlation threshold
    file(current).DetectionParameters.GenericFeaturesThresh = str2double(get(handles.featuresGT,'String')); % Features threshold
    %file(current).DetectionParameters.GenericTemplateAmplitudeCoef = str2double(get(handles.amplitude,'String'));

    % Patient Specific spike detection parameters
    file(current).DetectionParameters.PatientSpecificCrossCorrelationThresh = str2double(get(handles.crossCorrelationThresholdST,'String')); % Cross-correlation threshold
    file(current).DetectionParameters.PatientSpecificFeaturesThresh = str2double(get(handles.featuresST,'String')); % Features threshold
    file(current).DetectionParameters.PatientSpecificMinimumSWI = str2double(get(handles.minSWI,'String'));
    file(current).DetectionParameters.ClusterSelectionThresh = str2double(get(handles.clusterSelectionThresh,'String'));
    file(current).DetectionParameters.CheckThresh = str2double(get(handles.CheckThresh,'String')); %Spikes_check Threshold
    
    close(gcf);
    save('Spikes.mat','file');
end

        
end
